<?xml version="1.0"?>
<robot name="transport_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="base_length" value="0.4"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.1"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"><color rgba="0 0 1 1"/></material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
    </inertial>
  </link>

  <!-- 4 Omnidirectional Wheels -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="gray"><color rgba="0.5 0.5 0.5 1"/></material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} -${base_height/2}" rpy="0 1.5708 0"/>
      <axis xyz="0 0 1"/>  <!-- Wheel rotation axis (Z axis in local frame) -->
    </joint>
  </xacro:macro>


  <!-- Front Left -->
  <xacro:wheel name="wheel_fl" x="${base_length/2}" y="${base_width/2}"/>
  <!-- Front Right -->
  <xacro:wheel name="wheel_fr" x="${base_length/2}" y="-${base_width/2}"/>
  <!-- Rear Left -->
  <xacro:wheel name="wheel_rl" x="-${base_length/2}" y="${base_width/2}"/>
  <!-- Rear Right -->
  <xacro:wheel name="wheel_rr" x="-${base_length/2}" y="-${base_width/2}"/>

<gazebo>
  <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
    <ros>
      <namespace>/</namespace>
    </ros>
    <update_rate>50</update_rate>
    <left_joint>wheel_rl_joint</left_joint>
    <right_joint>wheel_rr_joint</right_joint>
    <wheel_separation>0.4</wheel_separation> <!-- Adjust as per your robot -->
    <wheel_radius>0.05</wheel_radius>
    <cmd_vel_topic>/cmd_vel</cmd_vel_topic>
    <odometry_topic>/odom</odometry_topic>
    <odometry_frame>odom</odometry_frame>
    <robot_base_frame>base_link</robot_base_frame>
    <publish_tf>true</publish_tf>
  </plugin>
</gazebo>

</robot>
